// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqgchfqclwvswcnjrdpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZ2NoZnFjbHd2c3djbmpyZHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzI3ODksImV4cCI6MjA1NTQ0ODc4OX0.vd6_TbUT5P0FpWk8g2ljmEQBhr7cvW5YK8ei-shggKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);